# Generated by Django 5.2.7 on 2025-10-30 02:48

import django.db.models.deletion
import teachingload.models.target_sdgs_models
import teachingload.models.teaching_load_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicrecord', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=teachingload.models.target_sdgs_models.get_upload_path_sdg)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('unit', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=teachingload.models.teaching_load_models.get_upload_path_subject_photo)),
                ('is_coil', models.BooleanField(default=False)),
                ('is_hali', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('max_enrollee', models.IntegerField()),
                ('current_enrollee', models.IntegerField()),
                ('duration', models.CharField(max_length=255)),
                ('partner_institution', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('target_sdgs', models.ManyToManyField(related_name='subjects', to='teachingload.sdg')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_load_schedules', to='academicrecord.semester')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingload.scheduletype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingload.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_enrollee', models.IntegerField()),
                ('current_enrollee', models.IntegerField()),
                ('duration_start', models.DateField()),
                ('duration_end', models.DateField()),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicrecord.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingload.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_subject_offerings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
