# Generated by Django 5.2.7 on 2025-11-05 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicrecord', '0001_initial'),
        ('teachingload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject_offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_subject_offerings', to='teachingload.subjectoffering'),
        ),
        migrations.AddField(
            model_name='gradingperiod',
            name='academic_term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicrecord.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='gradingperiodcategory',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='gradingperiod',
            name='grading_period_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicrecord.gradingperiodcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('academic_year_id', 'academic_term_category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student_id', 'subject_offer_id', 'academic_term_id')},
        ),
        migrations.AlterUniqueTogether(
            name='gradingperiod',
            unique_together={('academic_term_id', 'grading_period_category_id')},
        ),
    ]
