# Generated by Django 5.2.7 on 2025-10-30 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicrecord', '0001_initial'),
        ('teachingload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_subject_offerings', to='teachingload.subjectoffering'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academicrecord.academicyear'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semester_enrollments', to='academicrecord.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='semestercategory',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academicrecord.semestercategory'),
        ),
        migrations.AddField(
            model_name='term',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicrecord.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='termcategory',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='term',
            name='term_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicrecord.termcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'subject_offering', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester_category')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('semester', 'term_category')},
        ),
    ]
